### ISSUE TITLE
After adding repository and trying 'require' line, Invalid Argument Exception error

### ISSUE THREAD

**Issue by jamminjames** [openupmedia/oum_cookie_compliance#1]
I added the repository to composer.json, as shown. But when I use:
`composer require openupmedia/oum_cookie_compliance`
... I get this:
```
  [InvalidArgumentException]
  Could not find a version of package openupmedia/oum_cookie_compliance match
  ing your minimum-stability (stable). Require it with an explicit version co
  nstraint allowing its desired stability.
```
Please help. Thanks!

**Comment by tijsdeboeck** [comment]
Hi James,

You have "minimum-stability" set to stable, which doesn't allow for dev versions. Since there isn't a stable version of this module at the moment you should change it to "minimum-stability": "dev"

That should do the trick.

We'll release the module on Drupal.org in the near future btw, that will be easier ;)

**Comment by jamminjames** [comment]
Is the code for a Drupal CMS? I'm not using that.

**Comment by jamminjames** [comment]
What I have in the composer.json is:
```
  "repositories": [
     {
         "type": "vcs",
         "url": "https://github.com/openupmedia/oum_cookie_compliance.git"
     }
  ],
```
Are you saying that needs to be changed somehow? Should I replace  "type": "vcs" with "minimum-stability": "dev"?

Also, is this code meant for a Drupal CMS? I have a plain php website.

**Comment by tijsdeboeck** [comment]
Hi James,

This is indeed a Drupal module, so you won't be able to use it on a regular PHP project.

the "repositories" part is correct, but your composer.json can have a "minimum-stability" item as well, which defaults to "stable" if not set.
More info: https://getcomposer.org/doc/04-schema.md#minimum-stability
